/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sskings.app.gestor.financeiro.view.conta;

import br.com.sskings.app.gestor.financeiro.model.dao.AgenciaDao;
import br.com.sskings.app.gestor.financeiro.model.dao.ContaBancariaDao;
import br.com.sskings.app.gestor.financeiro.model.dto.AgenciaDto;
import br.com.sskings.app.gestor.financeiro.model.dto.ContaBancariaDto;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author s
 */
public class PainelConta extends javax.swing.JPanel {

    private final ContaBancariaDto conta;

    /**
     * Creates new form PainelConta
     */
    public PainelConta(ContaBancariaDto conta) {
        initComponents();
        this.conta = conta;
        preencherCampos();
        btnSalvar.setVisible(false);
    }

    private void preencherCampos() {

        switch (conta.getAgencia().getBanco().getNome()) {
            case "BB":
                ImageIcon iconBB = new ImageIcon("src/main/resources/images/logos/bancos/banco-do-brasil-logo.png");
                lblLogo.setText("");
                lblLogo.setIcon(iconBB);
                break;
            case "BRADESCO":
                ImageIcon iconBradesco = new ImageIcon("src/main/resources/images/logos/bancos/Logo-Banco-Bradesco.png");
                lblLogo.setText("");
                lblLogo.setIcon(iconBradesco);
                break;
            case "CAIXA":
                ImageIcon iconCaixa = new ImageIcon("src/main/resources/images/logos/bancos/caixa.png");
                lblLogo.setIcon(iconCaixa);
                lblLogo.setText("");
                break;
            case "DIGIO":
                ImageIcon iconDigio = new ImageIcon("src/main/resources/images/logos/bancos/Logotipo_digio.png");
                lblLogo.setText("");
                lblLogo.setIcon(iconDigio);
                break;
            case "ITAU":
                ImageIcon iconItau = new ImageIcon("src/main/resources/images/logos/bancos/itau.png");
                lblLogo.setIcon(iconItau);
                lblLogo.setText("");
                break;
            case "NUBANK":
                ImageIcon iconNu = new ImageIcon("src/main/resources/images/logos/bancos/nubank-logo-2.png");
                lblLogo.setIcon(iconNu);
                lblLogo.setText("");
                break;
            case "INTER":
                ImageIcon iconInter = new ImageIcon("src/main/resources/images/logos/bancos/inter.png");
                lblLogo.setIcon(iconInter);
                lblLogo.setText("");
                break;
            case "PAN":
                ImageIcon iconPan = new ImageIcon("src/main/resources/images/logos/bancos/pan.png");
                lblLogo.setIcon(iconPan);
                lblLogo.setText("");
                break;
            case "NEXT":
                ImageIcon iconNext = new ImageIcon("src/main/resources/images/logos/bancos/next.png");
                lblLogo.setIcon(iconNext);
                lblLogo.setText("");
                break;
            case "NEON":
                ImageIcon iconNeon = new ImageIcon("src/main/resources/images/logos/bancos/neon.png");
                lblLogo.setIcon(iconNeon);
                lblLogo.setText("");
                break;
            case "PICPAY":
                ImageIcon iconPicPay = new ImageIcon("src/main/resources/images/logos/bancos/picpay.png");
                lblLogo.setIcon(iconPicPay);
                lblLogo.setText("");
                break;
            case "SANTANDER":
                ImageIcon iconSantander = new ImageIcon("src/main/resources/images/logos/bancos/santander.png");
                lblLogo.setIcon(iconSantander);
                lblLogo.setText("");
                break;
            case "WILL":
                ImageIcon iconWill = new ImageIcon("src/main/resources/images/logos/bancos/will.png");
                lblLogo.setIcon(iconWill);
                lblLogo.setText("");
                break;
        }

        txtAgencia.setText(String.valueOf(conta.getAgencia().getCodigo()));
        txtNumero.setText(String.valueOf(conta.getNumero()));
        txtSaldo.setText(String.valueOf(conta.getSaldo()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblNomeDoBanco = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblAgencia = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        lblExcluirConta = new javax.swing.JLabel();
        lblEditarConta = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        lblLogo.setBackground(new java.awt.Color(153, 153, 153));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("LOGO");
        lblLogo.setOpaque(true);

        lblNomeDoBanco.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblNomeDoBanco.setText("CONTA DO {nome-do-banco}");

        lblNumero.setText("Número:");

        lblSaldo.setText("Saldo: R$ ");

        lblAgencia.setText("Agência:");

        txtAgencia.setEditable(false);
        txtAgencia.setBorder(null);

        txtNumero.setEditable(false);
        txtNumero.setBorder(null);

        txtSaldo.setEditable(false);
        txtSaldo.setBorder(null);
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });

        lblExcluirConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        lblExcluirConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExcluirConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExcluirContaMouseClicked(evt);
            }
        });

        lblEditarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        lblEditarConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditarContaMouseClicked(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(null);
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAgencia)
                        .addGap(3, 3, 3)
                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNomeDoBanco)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblExcluirConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEditarConta)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblExcluirConta, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(lblEditarConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeDoBanco)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(lblAgencia)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldo)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    private void lblExcluirContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluirContaMouseClicked
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o Cartão?");
        if (resp == 0) {
            try {
                new ContaBancariaDao().excluir(conta);
                JOptionPane.showMessageDialog(this, "Conta excluída!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao tentar excluir um cartão");
            }
        }

    }//GEN-LAST:event_lblExcluirContaMouseClicked

    private void lblEditarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarContaMouseClicked
        txtNumero.setEditable(true);
        txtAgencia.setEditable(true);
        txtSaldo.setEditable(true);
        btnSalvar.setVisible(true);
    }//GEN-LAST:event_lblEditarContaMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        if (!txtNumero.getText().isBlank() && !txtAgencia.getText().isBlank()
                && !txtSaldo.getText().isBlank()) {

            try {
                Long numero = Long.valueOf(txtNumero.getText());
                Double saldo = Double.valueOf(txtSaldo.getText());

                conta.getAgencia().setCodigo(Integer.valueOf(txtAgencia.getText()));
                AgenciaDto agencia = conta.getAgencia();
                new AgenciaDao().atualizar(agencia);
                new ContaBancariaDao().atualizar(conta);

                JOptionPane.showMessageDialog(this, "Os dados da conta foram atualizados.");

                txtNumero.setEditable(false);
                txtAgencia.setEditable(false);
                txtSaldo.setEditable(false);
                btnSalvar.setVisible(false);
                this.revalidate();
                this.repaint();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Não foi possivel atualizar os dados conta.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
        }
    }//GEN-LAST:event_btnSalvarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblEditarConta;
    private javax.swing.JLabel lblExcluirConta;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNomeDoBanco;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
