/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sskings.app.gestor.financeiro.view.banco;

import br.com.sskings.app.gestor.financeiro.model.dao.BancoDao;
import br.com.sskings.app.gestor.financeiro.model.dto.BancoDto;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sskings
 */
public class PainelBanco extends javax.swing.JPanel {
    
    private final BancoDto banco;

    /**
     * Creates new form PainelBanco
     */
    public PainelBanco(BancoDto banco) {
        initComponents();
        this.banco = banco;
        preencherCampos();
        btnSalvar.setVisible(false);   
    }
    
    private void preencherCampos(){
        
        switch(banco.getNome()){
            case "BB": 
                ImageIcon iconBB = new ImageIcon("src/main/resources/images/logos/bancos/banco-do-brasil-logo.png");
                LOGO.setText("");
                LOGO.setIcon(iconBB);
                break;
            case "BRADESCO":
                ImageIcon iconBradesco = new ImageIcon("src/main/resources/images/logos/bancos/Logo-Banco-Bradesco.png");
                LOGO.setText("");
                LOGO.setIcon(iconBradesco);
                break;
            case "CAIXA":
                ImageIcon iconCaixa = new ImageIcon("src/main/resources/images/logos/bancos/caixa.png");
                LOGO.setIcon(iconCaixa);
                LOGO.setText("");
                break;
            case "DIGIO":
                ImageIcon iconDigio = new ImageIcon("src/main/resources/images/logos/bancos/Logotipo_digio.png");
                LOGO.setText("");
                LOGO.setIcon(iconDigio);
                break;
            case "ITAU" :
                ImageIcon iconItau = new ImageIcon("src/main/resources/images/logos/bancos/itau.png");
                LOGO.setIcon(iconItau);
                LOGO.setText("");
                break;
            case "NUBANK" :
                ImageIcon iconNu = new ImageIcon("src/main/resources/images/logos/bancos/nubank-logo-2.png");
                LOGO.setIcon(iconNu);
                LOGO.setText("");
                break;
            case "INTER" :
                ImageIcon iconInter = new ImageIcon("src/main/resources/images/logos/bancos/inter.png");
                LOGO.setIcon(iconInter);
                LOGO.setText("");
                break;
            case "PAN" :
                ImageIcon iconPan = new ImageIcon("src/main/resources/images/logos/bancos/pan.png");
                LOGO.setIcon(iconPan);
                LOGO.setText("");
                break;
            case "NEXT" :
                ImageIcon iconNext = new ImageIcon("src/main/resources/images/logos/bancos/next.png");
                LOGO.setIcon(iconNext);
                LOGO.setText("");
                break;
            case "NEON" :
                ImageIcon iconNeon = new ImageIcon("src/main/resources/images/logos/bancos/neon.png");
                LOGO.setIcon(iconNeon);
                LOGO.setText("");
                break;
            case "PICPAY" :
                ImageIcon iconPicPay = new ImageIcon("src/main/resources/images/logos/bancos/picpay.png");
                LOGO.setIcon(iconPicPay);
                LOGO.setText("");
                break;
            case "SANTANDER" :
                ImageIcon iconSantander = new ImageIcon("src/main/resources/images/logos/bancos/santander.png");
                LOGO.setIcon(iconSantander);
                LOGO.setText("");
                break;
            case "WILL" :
                ImageIcon iconWill = new ImageIcon("src/main/resources/images/logos/bancos/will.png");
                LOGO.setIcon(iconWill);
                LOGO.setText("");
                break;
        }
        
        txtNome.setText(banco.getNome());
        txtCodigo.setText(banco.getCodigo().toString());
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOGO = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        lblEditar = new javax.swing.JLabel();
        lblExcluir = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        LOGO.setBackground(new java.awt.Color(204, 204, 255));
        LOGO.setText("LOGO");
        LOGO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LOGO.setMaximumSize(new java.awt.Dimension(50, 50));
        LOGO.setPreferredSize(new java.awt.Dimension(50, 50));

        lblNome.setText("NOME");

        lblCodigo.setText("CÓDIGO");

        txtNome.setEditable(false);

        txtCodigo.setEditable(false);

        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        lblEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditarMouseClicked(evt);
            }
        });

        lblExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        lblExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExcluirMouseClicked(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblCodigo))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(lblEditar)))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEditar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblExcluir))
                            .addComponent(lblCodigo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarMouseClicked
        txtNome.setEditable(true);
        txtCodigo.setEditable(true);
        btnSalvar.setVisible(true);
    }//GEN-LAST:event_lblEditarMouseClicked

    private void lblExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluirMouseClicked
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o Banco?");
        if(resp == 0){
            try{
                new BancoDao().excluir(banco);
                JOptionPane.showMessageDialog(this, "Banco excluído!");
            } catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Erro ao tentar excluir um Banco");
            }
        }
    }//GEN-LAST:event_lblExcluirMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        if(!txtNome.getText().isBlank() && !txtCodigo.getText().isBlank()) {            
            try{
                
                String nome = txtNome.getText();
                Integer codigo = Integer.valueOf(txtCodigo.getText());
                banco.setNome(nome);
                banco.setCodigo(codigo);
                new BancoDao().atualizar(banco);
                JOptionPane.showMessageDialog(this, "Os dados do banco foram atualizado.");
                                
                txtCodigo.setEditable(false);
                btnSalvar.setVisible(false);
                this.revalidate();
                this.repaint();
                
            }catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Não foi possivel atualizar os dados do banco.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
        }
    }//GEN-LAST:event_btnSalvarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
