/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sskings.app.gestor.financeiro.view.banco;

import br.com.sskings.app.gestor.financeiro.model.dao.BancoDao;
import br.com.sskings.app.gestor.financeiro.model.dto.BancoDto;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author sskings
 */
public class PainelListagemBanco extends javax.swing.JPanel {

    /**
     * Creates new form PainelListagemBanco
     */
    public PainelListagemBanco() {
        initComponents();
        listarBancos();
    }
    
    private void listarBancos() {
        try {
            List<BancoDto> listaDeBancos = new BancoDao().listar();

            if (!listaDeBancos.isEmpty()) {
                for (BancoDto banco : listaDeBancos) {
                    PainelBanco painelBanco = new PainelBanco(banco);
                    painelBanco.setSize(355, 100);
                    this.painelRenderizador.add(painelBanco);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Você não tem bancos cadastrados.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível listar os bancos");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        painelRenderizador = new javax.swing.JPanel();

        jScrollPane1.setViewportView(painelRenderizador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelRenderizador;
    // End of variables declaration//GEN-END:variables
}
