/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sskings.app.gestor.financeiro.view;

/**
 *
 * @author s
 */
public class PainelCreditos extends javax.swing.JPanel {

    /**
     * Creates new form PainelCreditos
     */
    public PainelCreditos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblProfessor = new javax.swing.JLabel();
        lblNomeProfessor = new javax.swing.JLabel();
        lblAluno2 = new javax.swing.JLabel();
        lblAluno3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAlunos = new javax.swing.JLabel();
        lblAluno1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(928, 520));

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        lblTitulo.setText("Créditos");

        lblProfessor.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblProfessor.setText("Professor:");

        lblNomeProfessor.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblNomeProfessor.setText("● Leonardo Melo");

        lblAluno2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblAluno2.setText("● Marcos Roberto");

        lblAluno3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblAluno3.setText("● Sérgio Santana");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/good-job.png"))); // NOI18N

        lblAlunos.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblAlunos.setText("Alunos:");

        lblAluno1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblAluno1.setText("● Maria Paula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfessor)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblNomeProfessor))
                    .addComponent(lblAlunos)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblAluno1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblAluno2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblAluno3)))
                .addGap(89, 89, 89)
                .addComponent(jLabel6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblProfessor)
                        .addGap(6, 6, 6)
                        .addComponent(lblNomeProfessor)
                        .addGap(28, 28, 28)
                        .addComponent(lblAlunos)
                        .addGap(12, 12, 12)
                        .addComponent(lblAluno1)
                        .addGap(6, 6, 6)
                        .addComponent(lblAluno2)
                        .addGap(6, 6, 6)
                        .addComponent(lblAluno3))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAluno1;
    private javax.swing.JLabel lblAluno2;
    private javax.swing.JLabel lblAluno3;
    private javax.swing.JLabel lblAlunos;
    private javax.swing.JLabel lblNomeProfessor;
    private javax.swing.JLabel lblProfessor;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
