/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sskings.app.gestor.financeiro.view;

/**
 *
 * @author s
 */
public class PainelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PainelPrincipal
     */
    public PainelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblTexto3 = new javax.swing.JLabel();
        lblTexto4 = new javax.swing.JLabel();
        lblTexto5 = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(928, 520));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(928, 520));

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblTitulo.setText("Seja bem vindo!");

        lblSubtitulo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblSubtitulo.setText("Aproveite as funcionalidades. ");

        lblTexto1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTexto1.setText("No IFinanças você pode:");

        lblTexto2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTexto2.setText("• Manter dados de contas bancárias.");

        lblTexto3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTexto3.setText("• Manter dados de cartões de crédito.");

        lblTexto4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTexto4.setText("• Manter dados de lançamentos. ");

        lblTexto5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTexto5.setText("•Gerar relatórios dos seus lançamentos.");

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img-view-principal.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblTitulo))
                    .addComponent(lblSubtitulo)
                    .addComponent(lblTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTexto2)
                    .addComponent(lblTexto3)
                    .addComponent(lblTexto4)
                    .addComponent(lblTexto5))
                .addGap(18, 18, 18)
                .addComponent(lblImg)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(59, 59, 59)
                        .addComponent(lblSubtitulo)
                        .addGap(58, 58, 58)
                        .addComponent(lblTexto1)
                        .addGap(12, 12, 12)
                        .addComponent(lblTexto2)
                        .addGap(6, 6, 6)
                        .addComponent(lblTexto3)
                        .addGap(6, 6, 6)
                        .addComponent(lblTexto4)
                        .addGap(6, 6, 6)
                        .addComponent(lblTexto5)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    private javax.swing.JLabel lblTexto4;
    private javax.swing.JLabel lblTexto5;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
