/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sskings.app.gestor.financeiro.view;

import br.com.sskings.app.gestor.financeiro.view.agencia.PainelPrincipalAgencia;
import br.com.sskings.app.gestor.financeiro.view.banco.PainelPrincipalBanco;
import br.com.sskings.app.gestor.financeiro.view.cartao.PainelPrincipalCartao;
import br.com.sskings.app.gestor.financeiro.view.conta.PainelPrincipalConta;
import br.com.sskings.app.gestor.financeiro.view.lancamentos.PainelPrincipalLancamentos;
import br.com.sskings.app.gestor.financeiro.view.relatorios.PainelPrincipalRelatorios;
import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author s
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaMenu() {
        initComponents();
        initContents();
    }

    private void initContents() {
        
        PainelPrincipal principal = new PainelPrincipal();
        principal.setSize(928, 520);
        principal.setLocation(0, 0);
        
        this.painelRenderizador.removeAll();
        this.painelRenderizador.add(principal);
        this.painelRenderizador.revalidate();
        this.painelRenderizador.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        btnContas = new javax.swing.JButton();
        btnCartoes = new javax.swing.JButton();
        btnLancamentos = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();
        btnCreditos = new javax.swing.JButton();
        btnPrincipal = new javax.swing.JButton();
        btnAgencias = new javax.swing.JButton();
        btnBancos = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        painelRenderizador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setLocationByPlatform(true);

        background.setBackground(new java.awt.Color(204, 204, 255));

        menu.setBackground(new java.awt.Color(255, 255, 255));

        btnContas.setBackground(new java.awt.Color(204, 204, 255));
        btnContas.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        btnContas.setForeground(new java.awt.Color(255, 255, 255));
        btnContas.setText("CONTAS BANCÁRIAS");
        btnContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContasActionPerformed(evt);
            }
        });

        btnCartoes.setBackground(new java.awt.Color(204, 204, 255));
        btnCartoes.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        btnCartoes.setForeground(new java.awt.Color(255, 255, 255));
        btnCartoes.setText("CARTÕES DE CRÉDITO");
        btnCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartoesActionPerformed(evt);
            }
        });

        btnLancamentos.setBackground(new java.awt.Color(204, 204, 255));
        btnLancamentos.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        btnLancamentos.setForeground(new java.awt.Color(255, 255, 255));
        btnLancamentos.setText("LANÇAMENTOS");
        btnLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancamentosActionPerformed(evt);
            }
        });

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO.png"))); // NOI18N

        btnCreditos.setBackground(new java.awt.Color(204, 204, 255));
        btnCreditos.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        btnCreditos.setForeground(new java.awt.Color(255, 255, 255));
        btnCreditos.setText("CRÉDITOS");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });

        btnPrincipal.setBackground(new java.awt.Color(204, 204, 255));
        btnPrincipal.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        btnPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipal.setText("PRINCIPAL");
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        btnAgencias.setBackground(new java.awt.Color(204, 204, 255));
        btnAgencias.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        btnAgencias.setForeground(new java.awt.Color(255, 255, 255));
        btnAgencias.setText("AGÊNCIAS");
        btnAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenciasActionPerformed(evt);
            }
        });

        btnBancos.setBackground(new java.awt.Color(204, 204, 255));
        btnBancos.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        btnBancos.setForeground(new java.awt.Color(255, 255, 255));
        btnBancos.setText("BANCOS");
        btnBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBancosActionPerformed(evt);
            }
        });

        btnRelatorios.setBackground(new java.awt.Color(204, 204, 255));
        btnRelatorios.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        btnRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorios.setText("RELATÓRIOS");
        btnRelatorios.setPreferredSize(new java.awt.Dimension(88, 23));
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });

        btnUsuario.setBackground(new java.awt.Color(204, 204, 255));
        btnUsuario.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setText("USUÁRIO");
        btnUsuario.setPreferredSize(new java.awt.Dimension(88, 23));
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLancamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCartoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(btnCreditos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgencias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBancos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCartoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLancamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBancos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        painelRenderizador.setBackground(new java.awt.Color(204, 204, 255));
        painelRenderizador.setPreferredSize(new java.awt.Dimension(928, 520));
        painelRenderizador.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(painelRenderizador, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelRenderizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        painelRenderizador.getAccessibleContext().setAccessibleParent(painelRenderizador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
        PainelPrincipal principal = new PainelPrincipal();
        principal.setSize(928, 520);
        principal.setLocation(0, 0);
        
        this.painelRenderizador.removeAll();
        this.painelRenderizador.add(principal);
        this.painelRenderizador.revalidate();
        this.painelRenderizador.repaint();
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        PainelCreditos creditos = new PainelCreditos();
        creditos.setSize(928, 520);
        creditos.setLocation(0, 0);
        
        this.painelRenderizador.removeAll();
        this.painelRenderizador.add(creditos);
        this.painelRenderizador.revalidate();
        this.painelRenderizador.repaint();
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void btnCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartoesActionPerformed
        PainelPrincipalCartao cartoes = new PainelPrincipalCartao();
        cartoes.setSize(928, 520);
        cartoes.setLocation(0, 0);
        
        this.painelRenderizador.removeAll();
        this.painelRenderizador.add(cartoes);
        this.painelRenderizador.revalidate();
        this.painelRenderizador.repaint();
    }//GEN-LAST:event_btnCartoesActionPerformed

    private void btnContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContasActionPerformed
        PainelPrincipalConta contas = new PainelPrincipalConta();
        contas.setSize(928, 520);
        contas.setLocation(0, 0);
        
        this.painelRenderizador.removeAll();
        this.painelRenderizador.add(contas);
        this.painelRenderizador.revalidate();
        this.painelRenderizador.repaint();
    }//GEN-LAST:event_btnContasActionPerformed

    private void btnLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancamentosActionPerformed
        PainelPrincipalLancamentos lancamentos = new PainelPrincipalLancamentos();
        lancamentos.setSize(928, 520);
        lancamentos.setLocation(0, 0);
        
        this.painelRenderizador.removeAll();
        this.painelRenderizador.add(lancamentos);
        this.painelRenderizador.revalidate();
        this.painelRenderizador.repaint();
    }//GEN-LAST:event_btnLancamentosActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        PainelPrincipalRelatorios relatorios = new PainelPrincipalRelatorios();
        relatorios.setSize(928, 520);
        relatorios.setLocation(0, 0);
        
        this.painelRenderizador.removeAll();
        this.painelRenderizador.add(relatorios);
        this.painelRenderizador.revalidate();
        this.painelRenderizador.repaint();
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenciasActionPerformed
        PainelPrincipalAgencia agencias = new PainelPrincipalAgencia();
        agencias.setSize(928, 520);
        agencias.setLocation(0, 0);
        
        this.painelRenderizador.removeAll();
        this.painelRenderizador.add(agencias);
        this.painelRenderizador.revalidate();
        this.painelRenderizador.repaint();
    }//GEN-LAST:event_btnAgenciasActionPerformed

    private void btnBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBancosActionPerformed
        PainelPrincipalBanco bancos = new PainelPrincipalBanco();
        bancos.setSize(928, 520);
        bancos.setLocation(0, 0);
        
        this.painelRenderizador.removeAll();
        this.painelRenderizador.add(bancos);
        this.painelRenderizador.revalidate();
        this.painelRenderizador.repaint();
    }//GEN-LAST:event_btnBancosActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        PainelUsuario usuario = new PainelUsuario();
        usuario.setSize(928, 520);
        usuario.setLocation(0, 0);
        
        this.painelRenderizador.removeAll();
        this.painelRenderizador.add(usuario);
        this.painelRenderizador.revalidate();
        this.painelRenderizador.repaint();
    }//GEN-LAST:event_btnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAgencias;
    private javax.swing.JButton btnBancos;
    private javax.swing.JButton btnCartoes;
    private javax.swing.JButton btnContas;
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnLancamentos;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel painelRenderizador;
    // End of variables declaration//GEN-END:variables

}
