/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sskings.app.gestor.financeiro.view;

import br.com.sskings.app.gestor.financeiro.model.dao.Validacao;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author s
 */
public class TelaLogin extends javax.swing.JFrame {

    private static String campoUsuario;

    private int xMouse;
    private int yMouse;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();

    }

    public static String getCampoUsuario() {
        return campoUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        headerD = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnSair = new javax.swing.JLabel();
        painelRenderizador = new javax.swing.JPanel();
        painelLogin = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pswSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblEsqueceuSenha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        painelLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        headerE = new javax.swing.JPanel();
        tabLogin = new javax.swing.JLabel();
        tabCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        headerD.setBackground(new java.awt.Color(255, 255, 255));
        headerD.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerDMouseDragged(evt);
            }
        });
        headerD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerDMousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnSair.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSair.setText("X");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerDLayout = new javax.swing.GroupLayout(headerD);
        headerD.setLayout(headerDLayout);
        headerDLayout.setHorizontalGroup(
            headerDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerDLayout.setVerticalGroup(
            headerDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        painelRenderizador.setPreferredSize(new java.awt.Dimension(410, 470));

        painelLogin.setBackground(new java.awt.Color(204, 204, 255));
        painelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Loma", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("INICIAR SESSÃO");
        painelLogin.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 44));

        lblUsuario.setFont(new java.awt.Font("Loma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setText("USUARIO");
        painelLogin.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 145, -1, 25));

        txtUsuario.setBackground(new java.awt.Color(204, 204, 255));
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setText("usuario ou email");
        txtUsuario.setBorder(null);
        txtUsuario.setOpaque(true);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        painelLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 205, 280, -1));

        lblSenha.setFont(new java.awt.Font("Loma", 1, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(51, 51, 51));
        lblSenha.setText("SENHA");
        painelLogin.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 276, -1, -1));

        pswSenha.setBackground(new java.awt.Color(204, 204, 255));
        pswSenha.setForeground(new java.awt.Color(153, 153, 153));
        pswSenha.setText("jPasswordField1");
        pswSenha.setBorder(null);
        pswSenha.setOpaque(true);
        pswSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pswSenhaMouseClicked(evt);
            }
        });
        pswSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswSenhaActionPerformed(evt);
            }
        });
        pswSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswSenhaKeyPressed(evt);
            }
        });
        painelLogin.add(pswSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 315, 280, 20));

        btnEntrar.setText("ENTRAR");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        painelLogin.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 376, 120, 50));

        lblEsqueceuSenha.setForeground(new java.awt.Color(51, 51, 51));
        lblEsqueceuSenha.setText("Esqueceu a senha ?");
        lblEsqueceuSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEsqueceuSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEsqueceuSenhaMouseClicked(evt);
            }
        });
        painelLogin.add(lblEsqueceuSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        painelLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 226, 280, 16));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        painelLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 340, 280, 10));

        javax.swing.GroupLayout painelRenderizadorLayout = new javax.swing.GroupLayout(painelRenderizador);
        painelRenderizador.setLayout(painelRenderizadorLayout);
        painelRenderizadorLayout.setHorizontalGroup(
            painelRenderizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        painelRenderizadorLayout.setVerticalGroup(
            painelRenderizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        painelLogo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carteira.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO.png"))); // NOI18N

        javax.swing.GroupLayout painelLogoLayout = new javax.swing.GroupLayout(painelLogo);
        painelLogo.setLayout(painelLogoLayout);
        painelLogoLayout.setHorizontalGroup(
            painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLogoLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(painelLogoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelLogoLayout.setVerticalGroup(
            painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLogoLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        headerE.setBackground(new java.awt.Color(255, 255, 255));
        headerE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerEMouseDragged(evt);
            }
        });
        headerE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headerEMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerEMousePressed(evt);
            }
        });

        tabLogin.setBackground(new java.awt.Color(204, 204, 255));
        tabLogin.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        tabLogin.setForeground(new java.awt.Color(51, 51, 51));
        tabLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tabLogin.setText("ENTRAR");
        tabLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabLogin.setOpaque(true);
        tabLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabLoginMouseClicked(evt);
            }
        });

        tabCadastro.setBackground(new java.awt.Color(255, 102, 102));
        tabCadastro.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        tabCadastro.setForeground(new java.awt.Color(51, 51, 51));
        tabCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tabCadastro.setText("CADASTRAR");
        tabCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabCadastro.setOpaque(true);
        tabCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCadastroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerELayout = new javax.swing.GroupLayout(headerE);
        headerE.setLayout(headerELayout);
        headerELayout.setHorizontalGroup(
            headerELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerELayout.createSequentialGroup()
                .addComponent(tabLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(tabCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerELayout.setVerticalGroup(
            headerELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tabCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelRenderizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(headerD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(painelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelRenderizador, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 865, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerDMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerDMousePressed

    private void headerDMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerDMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerDMouseDragged

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void headerEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_headerEMouseClicked

    private void headerEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerEMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerEMousePressed

    private void headerEMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerEMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerEMouseDragged

    private void tabCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCadastroMouseClicked
        PainelCadastroUsuario painel = new PainelCadastroUsuario();
        painel.setSize(410, 490);
        painel.setLocation(0, 0);

        painelRenderizador.removeAll();
        painelRenderizador.add(painel);
        painelRenderizador.revalidate();
        painelRenderizador.repaint();

    }//GEN-LAST:event_tabCadastroMouseClicked

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        txtUsuario.setText("");
        txtUsuario.setForeground(Color.black);
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        campoUsuario = txtUsuario.getText();
        char[] campoSenha = pswSenha.getPassword();

        if (!campoUsuario.isBlank() && campoSenha.length != 0) {
            try {
                boolean validouUsuario = new Validacao().validarUsuario(campoUsuario, campoSenha);
                boolean validouEmail = new Validacao().validarUsuarioPorEmail(campoUsuario, campoSenha);

                if (validouUsuario) {
                    TelaMenu principal = new TelaMenu();
                    principal.setVisible(true);
                    dispose();
                } else if (validouEmail) {
                    TelaMenu principal = new TelaMenu();
                    principal.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "nome de usuário ou senha inválido!");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao tentar validar o usuário!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos corretamente.");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void lblEsqueceuSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqueceuSenhaMouseClicked
        TelaRecuperacaoSenha recuperacao = new TelaRecuperacaoSenha();
        recuperacao.setVisible(true);
    }//GEN-LAST:event_lblEsqueceuSenhaMouseClicked
    private void tabLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabLoginMouseClicked

        painelRenderizador.removeAll();
        painelRenderizador.add(painelLogin);
        painelRenderizador.revalidate();
        painelRenderizador.repaint();
    }//GEN-LAST:event_tabLoginMouseClicked

    private void pswSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswSenhaActionPerformed

    }//GEN-LAST:event_pswSenhaActionPerformed

    private void pswSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswSenhaMouseClicked
        pswSenha.setText("");
        pswSenha.setForeground(Color.black);
    }//GEN-LAST:event_pswSenhaMouseClicked

    private void pswSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswSenhaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_pswSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel btnSair;
    private javax.swing.JPanel headerD;
    private javax.swing.JPanel headerE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEsqueceuSenha;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JPanel painelLogo;
    private javax.swing.JPanel painelRenderizador;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JLabel tabCadastro;
    private javax.swing.JLabel tabLogin;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
