/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sskings.app.gestor.financeiro.view.cartao;

import br.com.sskings.app.gestor.financeiro.model.dao.BancoDao;
import br.com.sskings.app.gestor.financeiro.model.dao.CartaoCreditoDao;
import br.com.sskings.app.gestor.financeiro.model.dao.UsuarioDao;
import br.com.sskings.app.gestor.financeiro.model.dto.BancoDto;
import br.com.sskings.app.gestor.financeiro.model.dto.CartaoCreditoDto;
import br.com.sskings.app.gestor.financeiro.model.dto.UsuarioDto;
import br.com.sskings.app.gestor.financeiro.view.TelaLogin;
import java.time.LocalDate; 
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author s
 */
public class PainelCadastroCartao extends javax.swing.JPanel {
    
    private Map<String, Integer> mapaBancoId = new HashMap<>();
    
    /**
     * Creates new form PainelCadastroCartao
     */
    public PainelCadastroCartao() {
        initComponents();
        preencherComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCartao = new javax.swing.JPanel();
        txtNumero = new javax.swing.JTextField();
        lblLogo = new javax.swing.JLabel();
        txtLimite = new javax.swing.JTextField();
        lblVencimento = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblLimite = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        txtMesV = new javax.swing.JTextField();
        txtAnoV = new javax.swing.JTextField();
        comboBancos = new javax.swing.JComboBox<>();
        lblBanco = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setRequestFocusEnabled(false);

        painelCartao.setBackground(new java.awt.Color(51, 51, 255));

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/master_card_icon.png"))); // NOI18N

        txtLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimiteActionPerformed(evt);
            }
        });

        lblVencimento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblVencimento.setForeground(new java.awt.Color(255, 255, 255));
        lblVencimento.setText("vencimento");

        lblNumero.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setText("número");

        lblLimite.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblLimite.setForeground(new java.awt.Color(255, 255, 255));
        lblLimite.setText("limite");

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards_sim_chip_icon_157314.png"))); // NOI18N

        comboBancos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblBanco.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        lblBanco.setForeground(new java.awt.Color(255, 255, 255));
        lblBanco.setText("BANCO");

        javax.swing.GroupLayout painelCartaoLayout = new javax.swing.GroupLayout(painelCartao);
        painelCartao.setLayout(painelCartaoLayout);
        painelCartaoLayout.setHorizontalGroup(
            painelCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCartaoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(painelCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCartaoLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblBanco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(lblLogo))
                    .addComponent(lblImagem))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCartaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCartaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painelCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumero)
                            .addComponent(lblLimite))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCartaoLayout.createSequentialGroup()
                        .addComponent(lblVencimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMesV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnoV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        painelCartaoLayout.setVerticalGroup(
            painelCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCartaoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(painelCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo)
                    .addComponent(lblBanco)
                    .addGroup(painelCartaoLayout.createSequentialGroup()
                        .addComponent(comboBancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(painelCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMesV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAnoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(painelCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(264, 264, 264))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(385, 385, 385))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(painelCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLimiteActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        if (!txtNumero.getText().isBlank() && !txtLimite.getText().isBlank()
                && !txtMesV.getText().isBlank() && !txtAnoV.getText().isBlank()) {

            try {

                Long numero = Long.valueOf(txtNumero.getText());
                Double limite = Double.valueOf(txtLimite.getText());
                Integer mesVencimento = Integer.valueOf(txtMesV.getText());
                Integer anoVencimento = Integer.valueOf(txtAnoV.getText());

                var usuarioLogado = new UsuarioDto();
                usuarioLogado.setLogin(TelaLogin.getCampoUsuario());
                usuarioLogado = new UsuarioDao().pesquisar(usuarioLogado);
                
                
                CartaoCreditoDto novoCartao = new CartaoCreditoDto();
                novoCartao.setNumero(numero);
                novoCartao.setUsuario(usuarioLogado);
                novoCartao.setVencimento(LocalDate.of(anoVencimento, mesVencimento, 1));
                novoCartao.setLimite(limite);
                novoCartao.setLimite_disponivel(limite);
                
                BancoDto banco = new BancoDto();
                banco.setId(getIdBancoSelecionado());
                novoCartao.setBanco(banco);

                new CartaoCreditoDao().cadastrar(novoCartao);
                JOptionPane.showMessageDialog(this, "Cartão cadastrado com sucesso!");
                txtNumero.setText("");
                txtLimite.setText("");
                txtMesV.setText("");
                txtAnoV.setText("");

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao tentar cadastrar um cartão");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos.");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    private void preencherComboBox(){
        try{
            List<BancoDto> bancos = new BancoDao().listar();
            comboBancos.removeAllItems();
            
            bancos.forEach(banco -> {
                
                comboBancos.addItem(banco.getNome());
                this.mapaBancoId.put(banco.getNome(), banco.getId());
                
            });
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Não foi possível preencher os bancos.");
        }
        
    }
    
    public int getIdBancoSelecionado() {
        String itemSelecionado = comboBancos.getSelectedItem().toString();
        return this.mapaBancoId.get(itemSelecionado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comboBancos;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblLimite;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblVencimento;
    private javax.swing.JPanel painelCartao;
    private javax.swing.JTextField txtAnoV;
    private javax.swing.JTextField txtLimite;
    private javax.swing.JTextField txtMesV;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
