/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sskings.app.gestor.financeiro.view.agencia;

import br.com.sskings.app.gestor.financeiro.model.dao.AgenciaDao;
import br.com.sskings.app.gestor.financeiro.model.dto.AgenciaDto;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sskings
 */
public class PainelAgencia extends javax.swing.JPanel {

    private final AgenciaDto agencia;

    /**
     * Creates new form PainelAgencia
     */
    public PainelAgencia(AgenciaDto agencia) {
        initComponents();
        this.agencia = agencia;
        preencherCampos();
        btnSalvar.setVisible(false);

    }

    private void preencherCampos() {

        switch (agencia.getBanco().getNome()) {
            case "BB":
                ImageIcon iconBB = new ImageIcon("src/main/resources/images/logos/bancos/banco-do-brasil-logo.png");
                lblLogo.setText("");
                lblLogo.setIcon(iconBB);
                break;
            case "BRADESCO":
                ImageIcon iconBradesco = new ImageIcon("src/main/resources/images/logos/bancos/Logo-Banco-Bradesco.png");
                lblLogo.setText("");
                lblLogo.setIcon(iconBradesco);
                break;
            case "CAIXA":
                ImageIcon iconCaixa = new ImageIcon("src/main/resources/images/logos/bancos/caixa.png");
                lblLogo.setIcon(iconCaixa);
                lblLogo.setText("");
                break;
            case "DIGIO":
                ImageIcon iconDigio = new ImageIcon("src/main/resources/images/logos/bancos/Logotipo_digio.png");
                lblLogo.setText("");
                lblLogo.setIcon(iconDigio);
                break;
            case "ITAU":
                ImageIcon iconItau = new ImageIcon("src/main/resources/images/logos/bancos/itau.png");
                lblLogo.setIcon(iconItau);
                lblLogo.setText("");
                break;
            case "NUBANK":
                ImageIcon iconNu = new ImageIcon("src/main/resources/images/logos/bancos/nubank-logo-2.png");
                lblLogo.setIcon(iconNu);
                lblLogo.setText("");
                break;
            case "INTER":
                ImageIcon iconInter = new ImageIcon("src/main/resources/images/logos/bancos/inter.png");
                lblLogo.setIcon(iconInter);
                lblLogo.setText("");
                break;
            case "PAN":
                ImageIcon iconPan = new ImageIcon("src/main/resources/images/logos/bancos/pan.png");
                lblLogo.setIcon(iconPan);
                lblLogo.setText("");
                break;
            case "NEXT":
                ImageIcon iconNext = new ImageIcon("src/main/resources/images/logos/bancos/next.png");
                lblLogo.setIcon(iconNext);
                lblLogo.setText("");
                break;
            case "NEON":
                ImageIcon iconNeon = new ImageIcon("src/main/resources/images/logos/bancos/neon.png");
                lblLogo.setIcon(iconNeon);
                lblLogo.setText("");
                break;
            case "PICPAY":
                ImageIcon iconPicPay = new ImageIcon("src/main/resources/images/logos/bancos/picpay.png");
                lblLogo.setIcon(iconPicPay);
                lblLogo.setText("");
                break;
            case "SANTANDER":
                ImageIcon iconSantander = new ImageIcon("src/main/resources/images/logos/bancos/santander.png");
                lblLogo.setIcon(iconSantander);
                lblLogo.setText("");
                break;
            case "WILL":
                ImageIcon iconWill = new ImageIcon("src/main/resources/images/logos/bancos/will.png");
                lblLogo.setIcon(iconWill);
                lblLogo.setText("");
                break;
        }

        txtCodigo.setText(agencia.getCodigo().toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblEditar = new javax.swing.JLabel();
        lblExcluir = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblLogo.setText("LOGO");
        lblLogo.setMaximumSize(new java.awt.Dimension(50, 50));
        lblLogo.setMinimumSize(new java.awt.Dimension(50, 50));
        lblLogo.setPreferredSize(new java.awt.Dimension(50, 50));

        lblCodigo.setText("CÓDIGO");

        txtCodigo.setEditable(false);

        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        lblEditar.setText("x");
        lblEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditarMouseClicked(evt);
            }
        });

        lblExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        lblExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExcluirMouseClicked(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(lblExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarMouseClicked
        txtCodigo.setEditable(true);
        btnSalvar.setVisible(true);
    }//GEN-LAST:event_lblEditarMouseClicked

    private void lblExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExcluirMouseClicked
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir a Agência?");
        if (resp == 0) {
            try {
                new AgenciaDao().excluir(agencia);
                JOptionPane.showMessageDialog(this, "Agência excluída!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao tentar excluir uma Agência");
            }

        }
    }//GEN-LAST:event_lblExcluirMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        if (!txtCodigo.getText().isBlank()) {
            try {

                Integer codigo = Integer.valueOf(txtCodigo.getText());
                agencia.setCodigo(codigo);
                new AgenciaDao().atualizar(agencia);
                JOptionPane.showMessageDialog(this, "O dados da agência foram atualizados.");

                txtCodigo.setEditable(false);
                btnSalvar.setVisible(false);
                this.revalidate();
                this.repaint();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Não foi possivel atualizar os dados da agência.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
        }
    }//GEN-LAST:event_btnSalvarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
